name: Go

on:
  push:
    branches: [ cloudprovider-hetzner ]

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        run: "make build-in-docker"
        working-directory: cluster-autoscaler
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          context: cluster-autoscaler
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
          registry: ghcr.io
          repository: ${{ github.repository }}
          tag_with_ref: true
